# Generated by Django 4.2.3 on 2023-08-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='ddfdds', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
